### ISSUE TITLE
Allow Options to be added together.

### ISSUE THREAD

**Issue by kezabelle** [ojii/django-classy-tags#14]
Given a list of Options:
```
OPTS = Options(
    Argument(...), Argument(...),
)
```

It would be nice to use composability to build up option lists, somewhat similarly to how Django management commands can (though they have the luxury of just being tuples of options, I think?)

```
OPTS = Options(
    Argument(...), Argument(...),
)
OPTS2 = OPTS + Options(
    StringArgument(...), Flag(...),
)
```

This would require implementing the ```__add__``` method to ```Options```, and presumably explicitly tethering to only other ```Options``` instances, lest someone try passing in a tuple, or some other iterable that isn't appropriate.

Currently, doing so yields:
```
>>> from classytags.core import Options
>>> Options() + Options()
TypeError: unsupported operand type(s) for +: 'Options' and 'Options'
```

**Comment by ojii** [comment]
Fixed in 969d188
