### ISSUE TITLE
Allow Options instances to display a __repr__

### ISSUE THREAD

**Issue by kezabelle** [ojii/django-classy-tags#15]
Given a tuple of Arguments:
```
OPTS = (Argument('...'), Argument('...'), Argument('...'))
```
One can easily see a vague idea of what's contained:
```
>>> print(OPTS)  # calls __repr__
(<Argument: ...>, <Argument: ...>)
```
However, if those same arguments are marshalled into an Options object:
```
options = Options(*OPTS)
```
Then the ability to inspect the options list easily is lost:
```
>>> print(options)
<classytags.core.Options object at 0xSomeMemoryOffset>
```

Realistically, it's a little thing, but it means documenting options via Sphinx doesn't work, which is a shame for internally documenting projects, which is how I came to find this.

**Comment by ojii** [comment]
fixed in 05f5087
