### ISSUE TITLE
InclusionTag may leak context state?

### ISSUE THREAD

**Issue by kezabelle** [ojii/django-classy-tags#16]
If I have an inclusion tag which does the following:
```
# name=tag1
def get_context(self, context, *args, **kwargs):
    context.update(test=1)
    return context
```
and a second template tag:
```
# name=tag2
def get_context(self, context, *args, **kwargs):
    context.update(test=2)
    return context
```
Then the state of the context may leak between, and after, the template tags are called, I think, eg:
```{% tag1 %} {% tag2 %} {{ test }}```
would display **2** for test, while
```{% tag2 %} {% tag1 %} {{ test }}```
would yield **1**.

Overall, I'd actually have expected `{{ test }}` to be blank, after the fact, as it's not an explicit `AsTag`, and may thus be clobbering existing values.

Off the top of my head, I think the `InclusionTag`'s `render_tag` method could be changed to something like:
```
template = self.get_template(context, **kwargs)
context.push()
data = self.get_context(context, **kwargs)
context.pop()
output = render_to_string(template, data)
```
(this can't be done *inside* the subclass's `get_context`, because it would pop off whatever has just been set onto it)

Edit:
----------------

I'm not sure what Django's own inclusion tags do in this scenario, as I've not used anything but classytags in years, so I suppose this may be mirroring their implementation ...

**Comment by ojii** [comment]
This was implemented with ``InclusionTag.push_context``, if that doesn't suffice, please re-open.
