### ISSUE TITLE
Not sure how this would work, but..

### ISSUE THREAD

**Issue by lighth7015** [ojii/django-classy-tags#19]
So I'm in the middle of working on a project with several apps, and I'd like to be able to display "remote" content in my views without having to muck about in the details of actually defining what it means to display something "remotely".

(NOTE: The distinction of *Local* vs. *Remote* is, in this case, relative to the app in question or not actual, factual, remote content.)

---
ClsidComponentView.py:
```python

@register.tag
class ClsidComponentView(InclusionTag):
	template = 'ClsidLookupError.html'
	name = 'Avalon.ClsidComponentView'
	
	options = Options(
		Argument( 'prop_lhs', resolve = False ),
		'=',
		Argument( 'prop_rhs', resolve = False ),
		blocks =[
			BlockDefinition( 'content', \
					VariableBlockName('endblock %(value)s', 'prop_lhs'), \
					'endblock')
		]
	)
	
	def get_context(self, context):
		return { "Section", "Foo" }
	
	def render_tag(self, context, prop_lhs, prop_rhs, block_name, content):
		print('Property %s = "%s".' %( prop_lhs, prop_rhs ))
		
		## 
		## This space intentionally left blank.
		## 
		
		context.push()
		document = content.render(context)
		
		context.pop()
		return document
```

HOWEVER, when I try using this, I get 

IndexError at /admin/
=============

pop from empty list
-------------

|                        	|                                                                                 	|
|--------------------:	|---------------------------------------------------------------------------------	|     Request Method: 	| GET                                                                             	|
|        Request URL: 	| http://(Server Name):8000/admin/                                                	|
|     Django Version: 	| 1.6.2                                                                           	|
|     Exception Type: 	| IndexError                                                                      	|
|    Exception Value: 	| pop from empty list                                                             	|
| Exception Location: 	| /usr/lib/python3.3/site-packages/classytags/parser.py in parse_blocks, line 192 	|
|  Python Executable: 	| /usr/bin/python                                                                 	|
|     Python Version: 	| 3.3.5                                                                           	|
|        Python Path: 	| ['/home/PSIGLENMERE/rudy.valencia/core/Callaway',                               	|
|                     	| '/usr/lib/python3.3/site-packages/django_divioadmin-0.2.3-py3.3.egg',           	|
|                     	| '/usr/lib/python33.zip',                                                        	|
|                     	| '/usr/lib/python3.3',                                                           	|
|                     	| '/usr/lib/python3.3/plat-linux',                                                	|
|                     	| '/usr/lib/python3.3/lib-dynload',                                               	|
|                     	| '/usr/lib/python3.3/site-packages',                                             	|
|                     	| '/home/PSIGLENMERE/rudy.valencia/core/Callaway']                                	|
|        Server time: 	| Sun, 6 Apr 2014 16:51:15 +0000                                                  	|
---
What am I doing to trigger this?

Thanks!
\- Robert

**Comment by ojii** [comment]
never got the full traceback/template, closing this.
