### ISSUE TITLE
allow use MultiValueArgument and MultiKeywordArgument together without word_breakpoint

### ISSUE THREAD

**Issue by vivazzi** [ojii/django-classy-tags#39]
Hi! Thank's for great library!

I want use MultiValueArgument and MultiKeywordArgument together like this:
```
class MyTag(Tag):
    name = 'my_tag'
    options = Options(
        MultiValueArgument('args'),
        MultiKeywordArgument('kwargs'),
        blocks=[('end_my_tag', 'nodelist')],
    )

    def render_tag(self, context, args, kwargs, nodelist):
        # some logic ...
        return some_result

# in template
{% my_tag var_1 var_2 key_1=v_1 key=v_2 %}
```

But in case I get error with parsing of arguments: MultiValueArgument takes all 'var_1 var_2 key_1=v_1 key=v_2' and can not parse 'key_1=v_1':
```
TemplateSyntaxError at /.../
Could not parse the remainder: '=v_1' from 'key_1=v_1'
```

To decide this bug it need use 'word_breakpoint' like this:
```
class MyTag(Tag):
    name = 'my_tag'
    options = Options(
        MultiValueArgument('args'),
        'word_breakpoint',
        MultiKeywordArgument('kwargs'),
        blocks=[('end_my_tag', 'nodelist')],
    )

    def render_tag(self, context, args, kwargs, nodelist):
        # some logic ...
        return some_result

# in template
{% my_tag var_1 var_2 word_breakpoint key_1=v_1 key=v_2 %}
```

But this solution need to use  'word_breakpoint'.

**Comment by ojii** [comment]
How would it know when to stop parsing your "args" without you telling it where it stops? Explicit really is better than implicit, maybe use a shorter breakword?

If the existence of the `=` character in an argument means it should switch modes, you can probably use something like this:

```python

class MagicMultiValueArgument(MultiValueArgument):
    def parse(self, parser, token, tagname, kwargs):
        """
        Parse a token.
        """
        value = self.value_class(self.parse_token(parser, token))
        if '=' in value:
            return False
        else:
            return super().parse(parser, token, tagname, kwargs)
```

**Comment by vivazzi** [comment]
I find solution for this issue: https://github.com/divio/django-cms/blob/develop/cms/templatetags/cms_tags.py#L1038

It looks like to your code. 

May be use your code for modification of MultiValueArgument?

**Comment by ojii** [comment]
The thing in django CMS looks better than what I wrote above.

It doesn't do this by default because it would break `{% mytag "arg=one" foo=bar %}`. You can just pass string constants as arguments and those could include `=` characters.

**Comment by vivazzi** [comment]
I see, it's interesting case. I'm agree.
Then maybe add additional some 'MagicMultiValueArgument' with Django CMS impliment to django-classy-tags? Or it's no good idea?

**Comment by ojii** [comment]
I would prefer not having it in classy-tags. There's absolutely nothing wrong with subclassing argument classes to meet your needs (actually: that's encouraged!).

**Comment by vivazzi** [comment]
OK, I see. I'm agree with you.
Thanks for having time for this ussie!
